import type { Metadata } from "next";
import { Rokkitt, Antic_Slab } from "next/font/google";
import "./globals.css";

const rokkittSans = Rokkitt({
  variable: "--font-rokkitt-sans",
  subsets: ["latin"],
});

const anticSlab = Antic_Slab({
  variable: "--font-antic-slab",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/pay.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rokkittSans.variable} ${anticSlab.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
